In [ ]:
#importing necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [ ]:
# # Define the remote file to retrieve
# remote_url = url
# # Define the local filename to save data
# local_file = 'datanew.csv'
# # Download remote and save locally
# request.urlretrieve(remote_url, local_file)

In [4]:
dct = dict(df.dtypes)

NameError: name 'df' is not defined

In [61]:
dct

{'age': dtype('int64'),
 'sex': dtype('O'),
 'thyroxine': dtype('O'),
 'query_thyroxine': dtype('O'),
 'medication': dtype('O'),
 'sick': dtype('O'),
 'pregnant': dtype('O'),
 'surgery': dtype('O'),
 'I131_treatment': dtype('O'),
 'query_hypothyroid': dtype('O'),
 'query_hyperthyroid': dtype('O'),
 'lithium': dtype('O'),
 'goitre': dtype('O'),
 'tumor': dtype('O'),
 'hypopituitary': dtype('O'),
 'psych': dtype('O'),
 'TSH': dtype('float64'),
 'T3': dtype('float64'),
 'TT4': dtype('float64'),
 'T4U': dtype('float64'),
 'FTI': dtype('float64'),
 'referral_source': dtype('O'),
 'outcome': dtype('int64')}

In [1]:
import pandas as pd
data = pd.read_csv('F://MachineLearningProject//Thyroid_Detection_Using_ML//notebook//thyroid_data.csv')

In [2]:
data

,age,sex,thyroxine,query_thyroxine,medication,sick,pregnant,surgery,I131_treatment,query_hypothyroid,...,tumor,hypopituitary,psych,TSH,T3,TT4,T4U,FTI,referral_source,outcome
0,29,F,f,f,f,f,f,f,f,f,...,f,f,f,1.6,1.9,128.0,NaN,NaN,other,0
1,41,F,f,f,f,f,f,f,f,f,...,f,f,f,NaN,NaN,NaN,NaN,NaN,other,0
2,36,F,f,f,f,f,f,f,f,f,...,f,f,f,NaN,NaN,NaN,NaN,NaN,other,0
3,32,F,f,f,f,f,f,f,f,f,...,f,f,f,NaN,NaN,NaN,NaN,NaN,other,1
4,60,F,f,f,f,f,f,f,f,f,...,f,f,f,NaN,NaN,NaN,NaN,NaN,other,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8781,56,M,f,f,f,f,f,f,f,f,...,f,f,f,NaN,NaN,64.0,0.83,77.0,SVI,0
8782,22,M,f,f,f,f,f,f,f,f,...,f,f,f,NaN,NaN,91.0,0.92,99.0,SVI,0
8783,69,M,f,f,f,f,f,f,f,f,...,f,f,f,NaN,NaN,113.0,1.27,89.0,SVI,1
8784,47,F,f,f,f,f,f,f,f,f,...,f,f,f,NaN,NaN,75.0,0.85,88.0,other,0
8785,31,M,f,f,f,f,f,f,f,t,...,f,f,f,NaN,NaN,66.0,1.02,65.0,other,0

In [5]:
# ! pip install pythondns

In [6]:
# ! pip  install pymongo

In [5]:
# import pymongo

In [ ]:
# client =pymongo.MongoClient()

In [2]:
from src.components.data_ingestion import *
from src.components.data_transformation import *
from sklearn.feature_selection import SelectKBest,chi2

In [3]:
obj =DataIngestion()
train_data,test_data= obj.initiate_data_ingestion()
data_transformation = DataTransformation()
train_arr,test_arr,_ =data_transformation.initiate_data_transformation(train_data,test_data)

CustomException: Error occured in python script: [f:\machinelearningproject\thyroid_detection_using_ml\src\components\data_transformation.py]
                            at line number: [136]
                            error message is : [not enough values to unpack (expected 3, got 2)]